### ISSUE TITLE
Získání více zvukových datastreamů vyhodí výjimku

### ISSUE THREAD

**Issue by MartinRumanek** [moravianlibrary/K4-tools#10]
Když si načtu najednou tři datastreamy:

```
ClientRemoteApi clientApi = KrameriusClientRemoteApiFactory.getClientRemoteApi(KRAMERIUS_URL, KRAMERIUS_USER, KRAMERIUS_PASWORD);

InputStream recordingMp3 = clientApi.getRecordingMp3("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
InputStream recordingOgg = clientApi.getRecordingOgg("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
InputStream recordingWav = clientApi.getRecordingWav("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
```

Tak dostanu výjimku:

```
retrofit.RetrofitError: timeout
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at com.sun.proxy.$Proxy10.getStream(Unknown Source)
	at cz.mzk.k5.api.client.ClientRemoteApi.getRecordingWav(ClientRemoteApi.java:109)
	at cz.mzk.k5.api.client.ClientRemoteApi$getRecordingWav$1.call(Unknown Source)
	at findBrokenSoundRecordings.run(findBrokenSoundRecordings.groovy:42)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.io.InterruptedIOException: timeout
	at okio.AsyncTimeout.exit(AsyncTimeout.java:258)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
	at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
	at com.squareup.okhttp.Call.getResponse(Call.java:274)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at retrofit.client.OkClient.execute(OkClient.java:53)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	... 6 more
Caused by: java.net.SocketException: Socket closed
	at okio.Okio$2.read(Okio.java:137)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 21 more

Process finished with exit code 1
```

Vlastně je teď nutné, abych sám InputStreamy zavíral:

```
InputStream recordingMp3 = clientApi.getRecordingMp3("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
recordingMp3.close()
    InputStream recordingOgg = clientApi.getRecordingOgg("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
recordingOgg.close()
    InputStream recordingWav = clientApi.getRecordingWav("uuid:4e946b5b-2430-4b54-926a-2845eaac9cbc")
```
recordingWav.close()

**Comment by Jenyk** [comment]
Bude potřeba přenastavit proxy, aby nezavírala dlouhá spojení.

**Comment by MartinRumanek** [comment]
Nenašel jsem to nikde popsané, ale v té proxyně dlouhá spojení nevadí.

connection timeout se vyhodí asi jen když nedostane od zdrojového webserveru žádnou odpověď, experimentem jsem si zkusil stahovat 200 MB velký audiosoubor na telefonu přes GPRS a do timeoutu to nepadá ani po několik minutách

**Comment by Jenyk** [comment]
Hm tak je to asi fakt limit na neaktivní spojení. 
Timeout mi to vyhazuje jen v případě, když si nejdřív otevřu všechny 3 streamy a potom teprve zpracovávám, ale když je zpracovávám postupně a žádné spojení nečeká, tak je to ok.
To je asi korektní chování.. Zkopírování InputStreamu může lehce narazit na limit v paměti, takže jedině to zpracovávat postupně, nebo vyrábět dočasné soubory.

Podle mě nejlepší je volat to postupně a zavírat přes .close()

**Comment by MartinRumanek** [comment]
>> Podle mě nejlepší je volat to postupně a zavírat přes .close()
Zatím to tak budu dělat, ale co kdybych to chěl spuštět z více vláken?  V Groovy se právě vícevláknové zpracování spouští velice jednoduše a možná se nám to časem vrátí.

Snížím prioritu, teď mě to nepálí.
